### ISSUE TITLE
Update conflict with wordpress.org plugin

### ISSUE THREAD

**Issue by pelmered** [Rarst/fragment-cache#7]
Hey,

Thanks for a great plugin!

When you have this plugins installed(I installed it with composer) you get an update notification for this plugin. But the plugin WordPress wants to update to is this plugin: https://wordpress.org/plugins/fragmentcache/ (version 0.6.0). 

I guess this plugin is matched by plugin name. Could you please change the plugin name to avoid this conflict? Add a prefix or something.

Thanks.

**Comment by Rarst** [comment]
That's what
```
"suggest": {
	"rarst/update-blocker": "Prevents invalid updates from official repositories"
},
```
part is for. :)

**Comment by pelmered** [comment]
Ah, yes. 
I thought that plugin blocked all updates from wordpress.org, and I did not want that, but now after looking at the code I see that is not the case. It could be a bit more clear regarding this. 

I will use that. Thank you.

**Comment by pelmered** [comment]
Actually, update-blocker did not work. I do not get a .git-folder in my fragment-cache directory when I install it with composer if I use normal version number
```
    "rarst/fragment-cache": "^1.2",
```
I need to use this if composer should clone the repo and add the .git-folder. This works good, but would prefer to use a tagged version:
```
    "rarst/fragment-cache": "dev-master",
```

What is your suggestion @Rarst ?

**Comment by Rarst** [comment]
I don't quite follow. Update Blocker just installs as separate plugin. However you find convenient — requiring in site's level Composer or just building separately. Or even just copying the file, it's porposely self-contained. 

What does `.git` has to do with it?

**Comment by pelmered** [comment]
If I read the code in Update Blocker correctly it only disables updates for plugins that have a `.git`, `.svn` or `.hg` folder in the root folder. That is correct, right?

The problem is, if I install for example the ’fragment-cache’ plugin using the version number (`"^1.2"`) i get no `.git` folder in my plugin folder and Update Blocker does nothing(composer is just getting a package, not a git repo). The Update Blocker plugin only works if I configure composer to clone the git-repo by using `"dev-master"` as version in my `composer.json`, because now I get a `.git` folder in my `fragment-cache` folder that the Update Blocker plugin detects and skips the updates.

**Comment by Rarst** [comment]
> If I read the code in Update Blocker correctly it only disables updates for plugins that have a  .git ,  .svn  or  .hg  folder in the root folder. That is correct, right?

That's its defaults, Fragment Cache explicitly opts into block via hook, see https://github.com/Rarst/fragment-cache/blob/master/php/class-plugin.php#L45

To be clear as long as you have Fragment Cache and Update Blocker both active it should just work. :) If it doesn't then I got a bug somewhere. :)
